package com.daviddj.proyecto_final_djl.ui.theme

import androidx.compose.ui.graphics.Color
val md_theme_light_primary = Color(0xFF9C27B0) // Púrpura
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFAB47BC)
val md_theme_light_onPrimaryContainer = Color(0xFF311B92) // Púrpura más oscuro
val md_theme_light_secondary = Color(0xFF8E24AA) // Púrpura más claro
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCE93D8)
val md_theme_light_onSecondaryContainer = Color(0xFF4CAF50) // Verde menta
val md_theme_light_tertiary = Color(0xFF9575CD)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE1BEE7)
val md_theme_light_onTertiaryContainer = Color(0xFF311B92) // Púrpura más oscuro
val md_theme_light_error = Color(0xFF9C27B0) // Púrpura
val md_theme_light_errorContainer = Color(0xFFFFD4D4)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF4CAF50) // Verde menta
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF212121)
val md_theme_light_surface = Color(0xFFFAFAFA)
val md_theme_light_onSurface = Color(0xFF212121)
val md_theme_light_surfaceVariant = Color(0xFFEDE7F6)
val md_theme_light_onSurfaceVariant = Color(0xFF424242)
val md_theme_light_outline = Color(0xFFB0BEC5)
val md_theme_light_inverseOnSurface = Color(0xFFE0E0E0)
val md_theme_light_inverseSurface = Color(0xFF1B1B1B)
val md_theme_light_inversePrimary = Color(0xFF673AB7) // Púrpura más oscuro
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8E24AA) // Púrpura más claro
val md_theme_light_outlineVariant = Color(0xFFCFD8DC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF673AB7) // Púrpura
val md_theme_dark_onPrimary = Color(0xFF311B92) // Púrpura más oscuro
val md_theme_dark_primaryContainer = Color(0xFF512DA8)
val md_theme_dark_onPrimaryContainer = Color(0xFF9C27B0) // Púrpura más claro
val md_theme_dark_secondary = Color(0xFF8E24AA) // Púrpura más claro
val md_theme_dark_onSecondary = Color(0xFF4A148C) // Púrpura más oscuro
val md_theme_dark_secondaryContainer = Color(0xFF5E35B1)
val md_theme_dark_onSecondaryContainer = Color(0xFF4CAF50) // Verde menta
val md_theme_dark_tertiary = Color(0xFF9FA8DA)
val md_theme_dark_onTertiary = Color(0xFF303F9F)
val md_theme_dark_tertiaryContainer = Color(0xFF3949AB)
val md_theme_dark_onTertiaryContainer = Color(0xFFE1BEE7)
val md_theme_dark_error = Color(0xFFD32F2F) // Rojo oscuro para resaltar
val md_theme_dark_errorContainer = Color(0xFF6D1B0B) // Rojo más oscuro
val md_theme_dark_onError = Color(0xFF450003) // Blanco para resaltar
val md_theme_dark_onErrorContainer = Color(0xFFFFD4D4)
val md_theme_dark_background = Color(0xFF1B1B1B)
val md_theme_dark_onBackground = Color(0xFFE0E0E0)
val md_theme_dark_surface = Color(0xFF1B1B1B)
val md_theme_dark_onSurface = Color(0xFFE0E0E0)
val md_theme_dark_surfaceVariant = Color(0xFF424242)
val md_theme_dark_onSurfaceVariant = Color(0xFFCFD8DC)
val md_theme_dark_outline = Color(0xFF757575)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1B)
val md_theme_dark_inverseSurface = Color(0xFFE0E0E0)
val md_theme_dark_inversePrimary = Color(0xFF8E24AA) // Púrpura más claro
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF8E24AA) // Púrpura más claro
val md_theme_dark_outlineVariant = Color(0xFF424242)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF8E24AA) // Semilla en un tono de púrpura
